### ISSUE TITLE
Unable to specify story format from a directory

### ISSUE THREAD

**Issue by ricpelo** [Dan-Q/twee2#11]
I want to use SugarCube 2 story format, so I try:

```console
$ ls -F
input.tw2  SC2/
$ ls SC2
format.js  icon.svg  LICENSE
$ cat input.tw2
::Configuration [twee2]
Twee2::build_config.story_format = './SC2'

::Start
Hello
$ twee2 version
   Your version: 0.4.2
 Latest version: 0.4.2
$ twee2 build input.tw2 output.html               
ERROR: story format './SC2' not found.
$ twee2 build input.tw2 output.html --format=./SC2
ERROR: story format './SC2' not found.
```

It doesn't work. Any clues?

Thanks!

**Comment by Dan-Q** [comment]
How very odd! I'd have expected it to work. Before I dive in and give it a go, can you try the following:

`twee2 build input.tw2 output.html --format=SC2`

`twee2 build input.tw2 output.html --format=\`pwd\`/SC2`

(neither should be necessary, but I'm just checking for the obvious)

Can you also check that you've got read permission on format.js - the easiest way to check this would be e.g.:

`head ./SC2/format.js`

Thanks!

**Comment by Dan-Q** [comment]
Ah! This is actually a bug! I've replicated it, and I think I see what's causing it. Working on a solution now.

**Comment by Dan-Q** [comment]
Okay - Twee2 v0.5.0 fixes this problem. To upgrade your installation of Twee2, run:

`gem install twee2`

You'll then be able to run:

`twee2 build input.tw2 output.html --format=./SC2`

v0.5.0 also bundles SugarCube2 as an output format, so you can now simply do:

`twee2 build input.tw2 output.html --format=SugarCube2`

Hope that helps.

**Comment by ricpelo** [comment]
Great! It works wonderfully! Thank you very much for your superfast reply :).
