### ISSUE TITLE
Updating SugarCube 2

### ISSUE THREAD

**Issue by huntsfromshadow** [Dan-Q/twee2#17]
The included sugarcube2 is 2.7

SugarCube2 is up to 2.12 can we either update SugarCube2
or have a way to include an external story format?

**Comment by KimikoMuffin** [comment]
You can actually update story formats yourself, by putting them in the "storyFormats" directory in the Twee2 install directory.

**Comment by falcon03** [comment]
I agree that the shipped SugarCube 2 version should be updated. In the meantime, could you provide more detailed instructions on how to update it manually?

**Comment by KimikoMuffin** [comment]
Someone asked how to update them manually, but they apparently deleted their comment, soooo ... here's the instructions anyway.

First, find out where Ruby was installed. On my Windows machine, it's to the tune of `C:\Ruby23-x64`, but this will obviously vary.

From within the root Ruby directory, head to the `lib/ruby/gems/<insert Ruby version number here>/gems/twee2-<insert Twee2 version number here>/storyFormats/` directory. This is where the story formats are stored; you may safely delete the `SugarCube-2` directory and replace it with the updated version.

Disclaimer: this isn't exactly future-proof, nor is it particularly foolproof; twee2 version 0.6.0 is going to be stored in a different directory from twee version 0.5.0 which was in a different directory from twee 0.4.2, so you can't just make a shortcut to storyFormats and forget about it. (I, uh, confess that I accidentally stumbled into this when I updated from 0.4.2 to 0.5.0 .............)

**Comment by estiens** [comment]
You can also include any format by passing a path to the folder it is in when you build

for example `twee2 build index.tw2 index.html --format=../MyFormat`

where MyFormat is a folder in the parent directory of your story that contains a format.js
