### ISSUE TITLE
Upgrading story formats?

### ISSUE THREAD

**Issue by Menti** [Dan-Q/twee2#2]
Twine 2.0.9 was released including a new version of Harlowe. How can we update the Harlowe version that twee2 uses? Thanks!

**Comment by karlh626** [comment]
up vote :-)

**Comment by alex-ball** [comment]
I was about to enter a bug report that using the 'link-reveal' macro would trigger an error:

> I can't run the macro 'link-reveal' because it doesn't exist.

but I see this was added in Harlowe 1.2.0, while the Harlowe bundled with twee2 is 1.1.1.

The workaround appears to be this:

1. Go to the [twinejs](https://bitbucket.org/klembot/twinejs/src) source code repository
2. Navigate to storyFormats/Harlowe
3. Grab the format.js file
4. Find your local install of the twee2 gem, and navigate to the storyFormats/Harlowe folder
5. Replace the format.js there with the new one you downloaded

When I get a chance I'll put together a pull request...

**Comment by Menti** [comment]
Thanks @alex-ball, that did it for the time being.

I hope that twee2 continues to get maintained and improved. There's categorically no way I could write my current project with plain Twine.

**Comment by Dan-Q** [comment]
Should now be done. Note that it's also possible to specify the story format to use (from any arbitrary directory) from the command line.
