### ISSUE TITLE
harlowe-2 support?

### ISSUE THREAD

**Issue by picobyte** [Dan-Q/twee2#22]
Would it be possible to add support for harlowe2?

I tried adding the format.js and icon.svg in the storyFormats/Harlowe2/ dir, (from twinejs/story-formats/harlowe-2.0.1/) and any file that contained the string, but that does not seem to be enough.

```
::Start
(set: $arr to (a: "hello", "world"))
(print: $arr's 1)
(for: each _item, ...$arr) [I say _item.]
```

**Comment by stuwillis** [comment]
Harlowe 2 support would be great. I'm trying to use it as a external format in the command line but Twee2 isn't liking it.

**Comment by stuwillis** [comment]
I've got the external format working. You need to copy the /formats/harlowe-2.0.0 directory out of the Twine2 package (if you're on OSX) and put it somewhere central. Then you can specify it as a story format via the command line or in the ::Configuration options.

e.g.

`twee2 build TESTFILE.tw2 TESTFILE.html --format=./formats/harlowe-2.0.0`
