### ISSUE TITLE
[FR] Create new directory if directory our HTML file is being output to does not exist

### ISSUE THREAD

**Issue by crownsedge** [Dan-Q/twee2#29]
Hello!

I'm using twee2 as part of a CI/CD environment. I've run into a minor snag a few times now where I have to output my result HTML file into a brand new directory, and forgot to create it first -- twee2 simply crashed instead of creating the necessary directory for the file to live in. It's a simple fix (just create the directory beforehand) but twee2 should be capable of handling this itself.

**If the directory that is specified for the output HTML file to be saved to does not exist when twee2 is run, twee2 should create it instead of crashing when trying to save the file.**

I figure I'll also tag @harvimt here, as it's their release-0.6.0 branch of twee2 that I've actually been using most recently. (I would have placed this on their repository, but it doesn't have issue tracking turned on.) For the record, I did notice the same behavior when I was using the stock 0.5.0 gem.

Thanks to everyone who's contributed code to this project for all your hard work! It's greatly appreciated.

**Comment by crownsedge** [comment]
I actually may end up submitting a pull request for this to @harvimt's repo if I can figure out the code myself, in hopes that code also ends up coming back upstream at some point. (My Ruby is ...very rusty, to say the least, but file IO seems like a simple enough prospect that I may as well give it a go.)

**Comment by harvimt** [comment]
It's literally a one-line change. Anyway, having one bug tracker is probably good.

I... don't really want to support this code anyway. (I started work on something similar in Python that supports .tws files, but doesn't support haml or sccs)

Hopefully Dan checks his email at some point?

**Comment by crownsedge** [comment]
You're the best! Much appreciated 😄

I'd keep an eye out on what you're working on, but because I'm working with source control for my project working with tws files directly probably isn't the best idea. (Being able to have a whole bunch of .tw2 files and include all of them has been really helpful in terms of organization.) If you do decide to support tw2 files, though, I'm certainly not married to ruby or twee2 and would love to give your project a looksee! If that ends up being the case, I can be reached [here](https://twitter.com/crownsedge) or [here](mailto:ruth@ruthharris.me). 😃
